"""
ai_validator.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: extraction/ai_validator.py

OLD import (still works):
  from ai_validator import SomeClass

NEW import (preferred):
  from extraction.ai_validator import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'ai_validator' from root is deprecated. "
    "Use 'from extraction.ai_validator import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from extraction.ai_validator import *
