"""
classification_dashboard.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: dashboards/classification_dashboard.py

OLD import (still works):
  from classification_dashboard import SomeClass

NEW import (preferred):
  from dashboards.classification_dashboard import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'classification_dashboard' from root is deprecated. "
    "Use 'from dashboards.classification_dashboard import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from dashboards.classification_dashboard import *
