"""
compare_extraction.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: analysis/compare_extraction.py

OLD import (still works):
  from compare_extraction import SomeClass

NEW import (preferred):
  from analysis.compare_extraction import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'compare_extraction' from root is deprecated. "
    "Use 'from analysis.compare_extraction import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from analysis.compare_extraction import *
