"""
config.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: core/config.py

OLD import (still works):
  from config import SomeClass

NEW import (preferred):
  from core.config import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'config' from root is deprecated. "
    "Use 'from core.config import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from core.config import *
