"""
db_diagnostic.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: data/db_diagnostic.py

OLD import (still works):
  from db_diagnostic import SomeClass

NEW import (preferred):
  from data.db_diagnostic import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'db_diagnostic' from root is deprecated. "
    "Use 'from data.db_diagnostic import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from data.db_diagnostic import *
