"""
db_manager.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: data/db_manager.py

OLD import (still works):
  from db_manager import SomeClass

NEW import (preferred):
  from data.db_manager import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'db_manager' from root is deprecated. "
    "Use 'from data.db_manager import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from data.db_manager import *
