"""
document_parser.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: extraction/document_parser.py

OLD import (still works):
  from document_parser import SomeClass

NEW import (preferred):
  from extraction.document_parser import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'document_parser' from root is deprecated. "
    "Use 'from extraction.document_parser import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from extraction.document_parser import *
