"""
evaluator.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: analysis/evaluator.py

OLD import (still works):
  from evaluator import SomeClass

NEW import (preferred):
  from analysis.evaluator import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'evaluator' from root is deprecated. "
    "Use 'from analysis.evaluator import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from analysis.evaluator import *
