"""
finetune_model.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: ml/finetune_model.py

OLD import (still works):
  from finetune_model import SomeClass

NEW import (preferred):
  from ml.finetune_model import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'finetune_model' from root is deprecated. "
    "Use 'from ml.finetune_model import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from ml.finetune_model import *
