"""
finetune_unsloth.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: ml/finetune_unsloth.py

OLD import (still works):
  from finetune_unsloth import SomeClass

NEW import (preferred):
  from ml.finetune_unsloth import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'finetune_unsloth' from root is deprecated. "
    "Use 'from ml.finetune_unsloth import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from ml.finetune_unsloth import *
