"""
fix_cache.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: data/fix_cache.py

OLD import (still works):
  from fix_cache import SomeClass

NEW import (preferred):
  from data.fix_cache import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'fix_cache' from root is deprecated. "
    "Use 'from data.fix_cache import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from data.fix_cache import *
