"""
main.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: core/main.py

OLD import (still works):
  from main import SomeClass

NEW import (preferred):
  from core.main import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8')

import warnings
warnings.warn(
    "Importing 'main' from root is deprecated. "
    "Use 'from core.main import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from core.main import *

if __name__ == "__main__":
    main()
