"""
marker_extractor.py - COMPATIBILITY SHIM (auto-generated by migrate_folders.py)
========================================================================
This file redirects imports to the new module location: extraction/marker_extractor.py

OLD import (still works):
  from marker_extractor import SomeClass

NEW import (preferred):
  from extraction.marker_extractor import SomeClass

TODO: Update your imports to use the new paths, then delete this shim.
"""
import warnings
warnings.warn(
    "Importing 'marker_extractor' from root is deprecated. "
    "Use 'from extraction.marker_extractor import ...' instead.",
    DeprecationWarning,
    stacklevel=2
)
from extraction.marker_extractor import *
