# OPTIMIZED PROMPTS
# Generated by prompt_optimizer.py
# Use these prompts in your extraction system

def get_optimized_prompt(field: str, text: str) -> str:
    """
    Get the optimized prompt for a specific field.
    """
    text_sample = text[:2000]  # Limit text length
    
    if field == 'phone':
        # Best strategy: strategy_1_international_priority (100.00% accuracy)
        # TODO: Copy the prompt from strategy_1_international_priority method
        pass

    if field == 'name':
        # Best strategy: strategy_1_header_focus (92.86% accuracy)
        # TODO: Copy the prompt from strategy_1_header_focus method
        pass

    if field == 'email':
        # Best strategy: strategy_1_simple (92.86% accuracy)
        # TODO: Copy the prompt from strategy_1_simple method
        pass

    if field == 'date_of_birth':
        # Best strategy: strategy_1_format_aware (100.00% accuracy)
        # TODO: Copy the prompt from strategy_1_format_aware method
        pass

    return ""
